### PR TITLE
Added fallback and retry tests

### PR DESCRIPTION
**Pull request by Ahmad-Ayyoub**

### CODE REVIEW

**Review by evelinec — COMMENTED** [review]
@Ahmad-Ayyoub Code review feedback: 
- [ ] The "getRetriesCounter" variable should be renamed according to convention. It's a variable name, can't start with a verb. Use "retryCounter". This variable should be private? 

- [ ] getSystemRetries() method is more intuitive to be getRetryCounter()

- [ ] methods.add("getCounter" => use the method name in 2. 

- [ ] retries.add("InventoryManager" => I think use "Inventory" as the key is good enough

- [ ] resetRetries() => resetRetryCounter()?

- [ ] private final String LOCALHOST = "localhost/";  => don’t need / for localhost? can you take a look at EndPointTest to see how to build these URLs constants

- [ ] “proertiesSize” is spelled wrong

- [ ] can you change the comments into javadoc? It’ll be neater

- [ ] declaring the number 4 as variable will help explain about this number, i.e., expectedHits

- [ ] at the end of testRetryGettingSystemProperties(), it’s good to reset counter too

**Review by gkertaseferi — COMMENTED** [review]
I am going to follow Eveline's feedback and make the changes she suggested on her code as we are running out of time and then create another PR.

**Review by gkertaseferi — APPROVED** [review]

**Comment by Ahmad-Ayyoub** [comment]
@gkertaseferi  please update points. Thanks

**Comment by evelinec** [comment]
@gkertaseferi can you check off the points in the review comment? Thanks.

**Pull request merged**
